os: osx
osx_image: xcode14.2
language: swift
script: xcodebuild clean build test -workspace QuizApp/QuizApp.xcworkspace -scheme "CI" -sdk iphonesimulator -destination 'platform=iOS Simulator,id=A8E66C5F-9973-4930-B4C9-16A66F330363,OS=16.2' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
